# Generated by Django 2.2.24 on 2021-11-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='Dod', upload_to=''),
        ),
    ]
